### ISSUE TITLE
gp_shared_buffer example

### ISSUE THREAD

**Issue by ib00** [bqqbarbhg/guppy#4]
Is there an example for how to use gp_shared_buffer (OpenCL or CUDA)?

**Comment by bqqbarbhg** [comment]
Heya! 

Turns out I didn't have any working example using `gp_shared_buffer`s, they should now be fixed for all platforms along with some other stuff so I recommend updating from the `main` branch.

I added an example in [examples/shared_memory](https://github.com/bqqbarbhg/guppy/tree/main/examples/shared_memory) about shared memory, covering both `gp_shared` and `gp_shared_buffer`.

**Comment by ib00** [comment]
Great! Thank you!
